name: "SkyTech Dashboard"
description: "Streamlined Dashboard for SkyTech installs (based on Tunet)"
version: "1.6.2"
slug: "skytech_dashboard"
url: "https://github.com/haydenlove001/SkyTech_Dashboard/"
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 3002
panel_icon: "mdi:view-dashboard-variant"
panel_title: "SkyTech"
ports:
  3002/tcp: null
ports_description:
  3002/tcp: "Web UI (Ingress recommended)"
options: {}
schema: {}
